### ISSUE TITLE
Domains don't resolve

### ISSUE THREAD

**Issue by titpetric** [aacebedo/dnsdock#119]
Hello,

I'm using the latest amd64 docker image. I've configured dnsdock to run as:

```
  dnsdock:
    image: aacebedo/dnsdock:latest-amd64
    restart: always
    networks:
      - projects-ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 172.18.0.1:53:53/udp
    command:
      - --verbose
      - --http=:80
      - --domain=docker.lan
```

The output confirms the settings:

```
services-dnsdock-1      | 08:37:47.968 | DEBUG ▶ Handling DNS requests for 'docker.lan'.
```

```
services-dnsdock-1      | 08:37:47.986 | DEBUG ▶ Added service: 'e4122f3eb76f44174fabbb358f814def3f642e50b16b39470cbbac2c168b78a0'
services-dnsdock-1      |                        Name:     services-dnsdock-1
services-dnsdock-1      |                        Aliases:  []
services-dnsdock-1      |                        IPs:      [172.18.0.10]
services-dnsdock-1      |                        TTL:      -1
services-dnsdock-1      |                        Provider: docker
```

Trying to resolve any particular docker host registered:

```
services-dnsdock-1      | 08:41:01.364 | DEBUG ▶ DNS request for query 'services-dnsdock-1.docker.lan' from remote '172.18.0.1:47981'
services-dnsdock-1      | 08:41:01.364 | DEBUG ▶ No DNS record found for query 'services-dnsdock-1.docker.lan'
```

I'm not sure what the misconfiguration may be. I've tried clearing `--domain`, using single-words (no `.`)...

Also tried with --environment=docker, --domain=local; trying to see if i can surface more data from the http server.

---

# host scene.nginx-php.docker.local
scene.nginx-php.docker.local has address 172.18.0.5
scene.nginx-php.docker.local mail is handled by 0 scene.nginx-php.docker.local.

# host scene.docker.local
Host scene.docker.local not found: 3(NXDOMAIN)

# host nginx-php.docker.local
nginx-php.docker.local has address 172.18.0.5
nginx-php.docker.local mail is handled by 0 nginx-php.docker.local.

I wish there was a flag to auto-alias just the docker container name, but not the image name. It's clear after a detailed read of the README, but not following least astonishment, I'd expect <container>.docker.local to be resolved.
