### ISSUE TITLE
Unable to run dnsdock due to "EADDRNOTAVAIL" error on docker-for-mac

### ISSUE THREAD

**Issue by vincentchalamon** [aacebedo/dnsdock#89]
Hi,

I'm trying to run dnsdock:v1.16.1-amd64 on docker-for-mac, but I always have the following error:
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint dnsdock (120520037b1d620dffbd11d1472e700194a3908daa1c40becb0623be0d2124d7): Error starting userland proxy: Bind for 172.17.0.1:53: unexpected error (Failure EADDRNOTAVAIL).
```

I tried with `172.17.0.1` (`bridge` network gateway) and other network IP addresses, I always have the same error.

**Environment:**
- docker for mac v1.12.5 (14777) stable 3e6f00c1dc
- docker v1.12.5, build 7392c3b
- docker-compose v1.9.0, build 2585387
- osx el capitan v10.11.6

**I don't have this error on docker-toolbox.**

**Comment by aacebedo** [comment]
Hi.

Can you give me the command line you use when instantiating your container ?

**Comment by vincentchalamon** [comment]
Hi @aacebedo,

I execute the following command

```bash
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.0.1:53:53/udp aacebedo/dnsdock:v1.16.1-amd64
```

**Comment by aacebedo** [comment]
Hi
Can you try without t the ip address of your docker interface (ie 172.17.0.1) ?

**Comment by vincentchalamon** [comment]
You mean without exposing any port?
```bash
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock aacebedo/dnsdock:v1.16.1-amd64
```

**Comment by vincentchalamon** [comment]
No error, but no ports binded.

**Comment by aacebedo** [comment]
I meant with the port but without the ip
-P 53:53

**Comment by aacebedo** [comment]
-p 53:53

**Comment by vincentchalamon** [comment]
No error, but how can I connect a container to it? For example [mailcatcher](https://hub.docker.com/r/schickling/mailcatcher/). I tried with the following commands, but I can't access to `http://mailcatcher.docker`:
```bash
docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 53:53/udp aacebedo/dnsdock:v1.15.0-amd64
docker run -d -l com.dnsdock.alias=mailcatcher.docker --name mailcatcher schickling/mailcatcher
```

I also created file `/etc/resolver/docker` and tried it in different ways: `nameserver 172.17.0.1` (bridge network gateway), `nameserver 172.17.0.2` (dnsdock container IP address), `nameserver 127.0.0.1`. Also with/without a route (`sudo route -n add…`)

**Comment by vincentchalamon** [comment]
Dnsdock container recognizes mailcatcher container, here is logs:
```bash
2016/12/27 13:17:12 Added service: 06aa6a03cd0c740b1545682801e4a716574116b248b60f309932579d9f805074 {mailcatcher mailcatcher 172.17.0.3 -1 [mailcatcher.docker]}
2016/12/27 13:17:12 Handling DNS requests for mailcatcher.docker.
```

**Comment by vincentchalamon** [comment]
It may works using `nameserver 127.0.0.1` on resolver, dnsdock detects call on `ping -c 1 mailcatcher.docker`:
```
2016/12/27 13:28:02 DNS request for query mailcatcher.docker from remote 172.17.0.1:50233
2016/12/27 13:28:02 DNS record found for mailcatcher.docker
2016/12/27 13:28:02 DNS record found for mailcatcher.docker
```
But still can't access mailcatcher:
```
PING mailcatcher.docker (172.17.0.3): 56 data bytes

--- mailcatcher.docker ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by aacebedo** [comment]
I think you shall use the docker label com.dnsdock.ip_addr on the container "mailcatcher" to enforce the ip address of the DNS responses to be the one of the docker host.

Lets say you have a machine with real IP Address 192.168.0.1
On this machine you install docker so you have a new network adapter with address 172.17.0.1 and containers will have addresses starting from 172.17.0.X. 
If you create a dnsdock container and you bind the port 53 from it to the host, you'll get dns responses when addressing requests on 192.168.0.1:53. However, dnsdock will return 172.17.0.3 for mailcatcher as the latter is also a container and it gets the ip address from the container's metadata. You can enforce a different ip in the response by applying the tag com.dnsdock.ip_addr on the mailcatcher container.
According to the dockerfile of mailcatcher, it exposes ports 1025 and 1080. So you shall bind ports 1025 and 1080 of the container to your host and use the label to give the public address of your docker host, you can do this with the following command:
`docker run -d -l com.dnsdock.alias=mailcatcher.docker -p 1025:1025 -p 1080:1080 -l com.dnsdock.ip_addr=192.168.0.1 --name mailcatcher schickling/mailcatcher`

**Comment by vincentchalamon** [comment]
Hi @aacebedo,

Thanks for your answer, it works but it forces me to bind ports with my local machine, which can cause conflicts (i.e. for another mysql container used in another project).

I want to use dnsdock to create a dedicated environment for my project (using docker-compose) as following:
- private network
- dnsdock running on this network
- mailcatcher, mysql, etc.: all my project containers without binding ports to prevent conflicts (i.e. I could run multiple mysql containers in the same network but using different alias)
- local resolver (on OSX) for DNS

**Comment by aacebedo** [comment]
ok.
When you talking about networks, are you talking about multiple machine or the same machine you use for you dev ?
If you talking about the same machine you shall be able to use dnsdock and the other containers without binding any port as the host and the containers shall have access to each others IP (if you're creating the containers on the same docker network)
If you are trying to access to the containers' instance from an external machine (ie different from the docker host), you have to modify iptables on the host and the routes on the external machines in order to access to the docker internal network.

PS: I do not own a Mac and I do not know exactly how macOS deals with DNS and how docker on mac works. Pay attention to the fact that docker on mac seems to use a VM to work, so you may experience weird issues with networking and binding. In addition according to the docs, there are some limitations on how networking works on this machine (https://docs.docker.com/docker-for-mac/networking/)

**Comment by vincentchalamon** [comment]
Docker for mac uses native virtualization (like linux), but docker toolbox requires a virtual machine (i.e. VirtualBox). This issue only occurs with docker for mac.

Here is my `docker-compose.yml` file:
```yml
version: '2'
services:
    dnsdock:
        image: aacebedo/dnsdock:v1.16.1-amd64
        command: --domain foo.bar
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 53:53/udp
    mailcatcher:
        image: schickling/mailcatcher
        labels:
            com.dnsdock.alias: foo.bar
```
I don't really understand which IP address I should put in `/etc/resolver/foo.bar`, and if I need to create a new route (`sudo route -n add -net…`)

**Comment by aacebedo** [comment]
There is no virtualization on docker for linux, the kernel itself provides the capabilities of creating process and user namespaces. That is one of the main differences between virtualization and containerization.
On docker for mac and according their docs, they switched from virtualbox to hyperkit, there is still a virtualization layer because the macOS kernel is not able to provide namespace capabilities.

To answer your question, just remind that dnsdock is a only a DNS resolver. If you want any machine to obtain IPs in DNS responses, it shall send its requests to the container in which dnsdock is running (ie the IP you shall put in your dns resolver is the one of the dnsdock container). Then the IP corresponding to the requested domain and contained in the DNS response given by dnsdock will be either the IP of the container itself, or the value you've given to the com.dnsdock.ip_addr label.

As mentionned in the docker for mac documentation there is now docker0 bridge interface on your macOS host as this interface is created within the hyperkit VM running docker. They also say that there are some issues about networking on this setup (ie you cannot have per container IP addressing on  Mac).
You may try to switch to docker-toolbox or to install a linux in a VM and use docker inside. You may also try to use traefik (https://traefik.io/) to reroute your domain traffic to different container's instances

**Comment by vincentchalamon** [comment]
That's a complete & clear answer, thank you 😃
I'm running both docker-for-mac & docker-toolbox on my machine, I'll switch this project on toolbox.
Thanks

**Comment by aacebedo** [comment]
Keep me posted about your XP with docker toolbox. It may be useful for other users of dnsdock as your usecase is one of the most used I believe :)

**Comment by vincentchalamon** [comment]
Running on toolbox. I have a private docker network for my project with dnsdock running on it to manage all my containers accessible by DNS. It's a full project using [API Platform](https://api-platform.com/), [Angular](https://angular.io/), [admin-on-rest](http://marmelab.com/admin-on-rest/) & [WordPress](https://fr.wordpress.org/).
Here is `docker-compose.yml` file (for privacy, I replaced real domain by `project.local`):
```yml
version: '2'

volumes:
    db: ~
    vendor: ~
    spa_node_modules: ~
    admin_node_modules: ~
    composer: ~

networks:
    default:
        ipam:
            config:
                - subnet: 172.20.200.0/24
                  gateway: 172.20.200.1

services:
    dnsdock:
        image: aacebedo/dnsdock:v1.16.1-amd64
        command: --domain project.local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 172.20.200.1:53:53/udp

    api:
        networks:
            default:
                aliases:
                    - api.project.local
        image: apipltfrm/demo
        volumes:
            - ./api:/app
            - vendor:/app/vendor
            - composer:/var/www/.composer
        environment:
            SYMFONY_ENV: dev
            DATABASE_HOST: mysql.project.local
            DATABASE_PASSWORD: pswd
            MAILER_HOST: mailcatcher.project.local:1025
            CORS_ALLOW_ORIGIN: http://foo.project.local
        labels:
            com.dnsdock.alias: api.project.local
        depends_on:
            - mysql

    spa:
        networks:
            default:
                aliases:
                    - foo.project.local
        image: suchja/angular-cli-docker
        command: npm run start -- --host 0.0.0.0 --port 80
        expose:
            - 80
        volumes:
            - ./spa:/home/app
            - spa_node_modules:/home/app/node_modules
        environment:
            NPM_CONFIG_LOGLEVEL: warn
        labels:
            com.dnsdock.alias: foo.project.local
        depends_on:
            - api

    admin:
        networks:
            default:
                aliases:
                    - admin.project.local
        image: node:6.6
        command: npm start -- --host 0.0.0.0 --port 80
        expose:
            - 80
        working_dir: /home/app
        volumes:
            - ./admin:/home/app
            - admin_node_modules:/home/app/node_modules
        environment:
            NPM_CONFIG_LOGLEVEL: warn
        labels:
            com.dnsdock.alias: admin.project.local
        depends_on:
            - api

    wordpress:
        networks:
            default:
                aliases:
                    - www.project.local
        image: wordpress
        environment:
            WORDPRESS_TABLE_PREFIX: foo_
            WORDPRESS_DB_HOST: mysql.project.local
            MAILER_HOST: mailcatcher.project.local:1025
            WORDPRESS_DB_NAME: foo
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: pswd
        labels:
            com.dnsdock.alias: www.project.local
        depends_on:
            - mysql

    mysql:
        networks:
            default:
                aliases:
                    - mysql.project.local
        image: mysql:5.7.8
        labels:
            com.dnsdock.alias: mysql.project.local
        environment:
            MYSQL_ROOT_PASSWORD: pswd
            MYSQL_DATABASE: foo
        volumes:
            - db:/var/lib/mysql:rw

    mailcatcher:
        networks:
            default:
                aliases:
                    - mailcatcher.project.local
        image: schickling/mailcatcher
        labels:
            com.dnsdock.alias: project.local
```

Running on OSX, I created `/etc/resolver/project.local` file with `nameserver 172.20.200.1`, and added a route to route network subnet to docker-machine IP, as following:
```bash
sudo route -n add -net 172.20.200.0 192.168.99.100
```

Everything works like a charm!

![image](http://i.memeful.com/media/post/4wbkVXM_700wa_0.gif)
