### ISSUE TITLE
Issue with DNS names on different levels

### ISSUE THREAD

**Issue by whitecolor** [aacebedo/dnsdock#91]
`docker-compose.yaml` contains two services with such definitions (stuff omitted)
```
service-client:
  labels:
    com.dnsdock.alias: "client.service.app.dev"

service:
  labels:  
    com.dnsdock.alias: service.app.dev
```

service-client container got IP 172.19.0.5
service container got IP 172.19.0.3

both address return two IP's:
```
> nslookup service.app.dev 127.0.0.1
Servidor:  localhost
Address:  127.0.0.1

Respuesta no autoritativa:
Nombre:  service.app.dev
Addresses:  172.19.0.5
          172.19.0.3


> nslookup client.serivce.app.dev 127.0.0.1
Servidor:  localhost
Address:  127.0.0.1

Respuesta no autoritativa:
Nombre:  client.service.app.dev
Addresses:  172.19.0.5
          172.19.0.3
```
