### ISSUE TITLE
Reuse docker-compose labels

### ISSUE THREAD

**Issue by bersace** [aacebedo/dnsdock#97]
Hi,

In my use case, I avoid exposing ports and prefer `.docker` resolution to launche several instances of compose project. This require to export an env var and reuse it as *region* in dnsdock.

``` bash
# .envrc
export COMPOSE_PROJECT_NAME=dev
```

``` yaml
version: '3'
services:
  app:
    labels:
      com.dnsdock.region: ${COMPOSE_PROJECT_NAME}
      com.dnsdock.name: app
```

What do you think of falling back `com.dnsdock.region` to `com.docker.compose.project` and `com.dnsdock.name` to `com.docker.compose.service.`

This allow to resolve service as close as possible to compose structure :

``` consoe
$ getent hosts app.$COMPOSE_PROJECT_NAME.docker
172.23.0.4      app.compose.docker
$
```

Thanks for dnsdock, it's a lot easier than playing with ports !
